/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    ConfirmPopup: typeof import('primevue/confirmpopup')['default']
    Dialog: typeof import('primevue/dialog')['default']
    DictForm: typeof import('./src/components/ui/DictForm.vue')['default']
    Editor: typeof import('primevue/editor')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Layout: typeof import('./src/components/layout/Layout.vue')['default']
    Message: typeof import('primevue/message')['default']
    ModuleCard: typeof import('./src/components/ui/ModuleCard.vue')['default']
    Options: typeof import('./src/components/ui/Options.vue')['default']
    OverlayPanel: typeof import('primevue/overlaypanel')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    Spinner: typeof import('./src/components/features/Spinner.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    Toast: typeof import('primevue/toast')['default']
  }
}
